### ISSUE TITLE
Won't work in Ubuntu after Bionic

### ISSUE THREAD

**Issue by DDzwiedziu** [nicklasb/gnome-keyring-import-export#4]
As they doesn't supply the typelib.

```❯ python3 gnome_keyring_import_export.py
gnome_keyring_import_export.py:55: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
Traceback (most recent call last):
  File "gnome_keyring_import_export.py", line 56, in <module>
    from gi.repository import GnomeKeyring
  File "/usr/lib/python3/dist-packages/gi/importer.py", line 131, in load_module
    raise ImportError('cannot import name %s, '
ImportError: cannot import name GnomeKeyring, introspection typelib not found
```

I'm just not sure if this is a real bug or just a me missing something in Python-GNOME-Ubuntu relations.

**Comment by nicklasb** [comment]
Hi @DDzwiedziu , you are right it seems, it has been replaced: 
https://askubuntu.com/questions/1080896/what-replaced-pythons-gnomekeyring-module-in-ubuntu-18-04-bionic

If you find a solution, don't hesitate to drop by with a PR, I don't do much with this repo currently.

**Comment by directentis1** [comment]
@DDzwiedziu @nicklasb 

I managed to fix the export function, it now works on my Ubuntu 22.04.
But for some reason, the import still doesn't work.
Hope someone to point me out.

https://github.com/nicklasb/gnome-keyring-import-export/pull/5
